### ISSUE TITLE
LQFP footprint pins have varying sizes

### ISSUE THREAD

**Issue by plaes** [KiCad/Housings_QFP.pretty#4]
I was starting a new project with STM32L0 uC which comes in various packages (LQFP64 and LQFP48 both with 0.5mm pitch and LQFP32 with 0.8mm pitch). ST's documentation suggests that the pad size for 0.5mm pitch should be (0.3 x 1.2)mm and for LQFP32 it should be (0.5x1.2)mm.

Unfortunately the pad sizes in this library didn't match sizes suggested by ST and are pretty inconsistent:
- LQFP with 0.4mm pitch
  - LQFP-64 - (1.2x0.24)mm
  - LQFP-128 - (1.0x0.2)mm
  - LQFP-176 - (1.0x0.23)mm
  - LQFP-216 - (1.12x0.24)mm
- LQFP with 0.5mm pitch (STM32L0 datasheets suggests (1.2x0.3)mm pads for LQFP-48 and -64)
  - LQFP-32 - (1.2x0.28)mm
  - LQFP-48 - (1.3x0.25)mm
  - LQFP-64 - (1.0x0.25)mm
  - LQFP-80 - (1.5x0.28)mm
  - LQFP-100 - (1.5x0.28)mm
  - LQFP-128 - (1.5x0.28)mm
  - LQFP-144 - (1.55x0.3)mm
  - LQFP-160 - (1.1x0.285)mm
  - LQFP-176 - (1.12x0.3)mm
  - LQFP-208 - (1.5x0.4)mm
- LQFP with 0.65mm pitch
  - LQFP-36 - (1.0x0.43)mm
  - LQFP-52-1EP - (1.18x0.4)mm
  - LQFP-52 - (1.0x0.25)mm
- LQFP with 0.8mm pitch (STM32L0 datasheet suggests (1.2x0.5)mm pads for LQFP-32)
  - LQFP-32 - (1.2x0.6)mm
  - LQFP-44 - (1.6x0.56)mm
  - LQFP-64 - (1.5x0.6)mm

I'm volunteering to clean up the footprints with 0.5mm and 0.8mm pitches if someone says that the values coming from ST docs are correct.

**Comment by CarlPoirier** [comment]
Hi,

I am in for some consistency. These footprints have been designed by @michal777 and IIRC are done following Microchip's document here: http://ww1.microchip.com/downloads/en/PackagingSpec/00049AR.pdf

If we can determine some good all-around pad sizes, that would be our best bet.

**Comment by plaes** [comment]
After a lot of googling my findings are following:
* Industry standard name for footprint is actually "Land pattern" ;)
* Current industry standard is IPC-7351B - "Generic Requirements for Surface Mount Design and Land Pattern Standard"
* There's a standard for density level (A, B or C) which determines the land pattern geometry. [More info in this blog post](http://blogs.mentor.com/tom-hausherr/blog/2011/01/28/pcb-design-perfection-starts-in-the-cad-library-part-12/). This would be actually nice to have - for example you design your first PCBs so you can hand-solder the stuff (Level A). And eventually when you move on to full production, you also use Level C footprints.

**Comment by CarlPoirier** [comment]
IIRC the density levels had been discussed at some point, but I can't find where. We had settled with level B mostly. The KLC already expresses this for the courtyard. Maybe we could also specify the pad sizes.

**Comment by michal777** [comment]
There is no reason to follow just ST recommendations. I followed recommendations from different manufacturers. There is reference in doc field. It mat be better to calculate pad sizes but I don't know how to do it.

**Comment by hackscribble** [comment]
Closing historic issue.
