### ISSUE TITLE
LQFP-64_10x10mm: Pin 1 Marker not visible

### ISSUE THREAD

**Issue by greenscreenflicker** [KiCad/Housings_QFP.pretty#9]
The PIN one marker of (Housings_QFP:LQFP-64_10x10mm_Pitch0.5mm) is not visible. It's removed by the manufacturer as it's too close to the pads. We should move the Pin1 marker line to the top.

(When I find time I'll provide a patch.)

**Comment by SchrodingersGat** [comment]
Check out https://github.com/KiCad/Housings_QFP.pretty/pull/11

* I have moved the pin-1 marker for each part
* Added component outline to F.Fab layer
* Added indication of pin-1 corner with circle on silkscreen layer

**Comment by CarlPoirier** [comment]
#11 is merged, closing this. Thanks @greenscreenflicker for reporting.
